# German translations for profitbricks-python-blockdevice package
# German messages for profitbricks-python-blockdevice.
# Copyright (C) 2013 THE profitbricks-python-blockdevice'S COPYRIGHT HOLDER
# This file is distributed under the same license as the profitbricks-python-blockdevice package.
# Frank Brehm <frank.brehm@profitbricks.com>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: profitbricks-python-blockdevice 0.4.3\n"
"Report-Msgid-Bugs-To: frank.brehm@profitbricks.com\n"
"POT-Creation-Date: 2015-01-21 22:22+0100\n"
"PO-Revision-Date: 2014-12-19 17:20+0100\n"
"Last-Translator: Frank Brehm <frank.brehm@profitbricks.com>\n"
"Language-Team: German\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: pb_blockdev/base.py:125
#, python-format
msgid "Path %r to check with fuser does not exists."
msgstr "Der mit fuser zu überprüfende Pfad %r existiert nicht."

#: pb_blockdev/base.py:159
#, python-format
msgid "Block device %(bd)r cannot be removed, because it's currently opened by "
      "some user space processes:"
msgstr ""
"Das Blockgerät %(bd)r kann nicht enfernt werden, da es gegenwärtig von "
"einigen Anwendungsprogrammen geöffnet ist:"

#: pb_blockdev/base.py:185
#, python-format
msgid "Block device %(bd)r cannot be removed, because it has currently holder "
      "devices:"
msgstr ""
"Das Blockgerät %(bd)r kann nicht enfernt werden, da gegenwärtig "
"Holder-Geräte existieren:"

#: pb_blockdev/base.py:214 pb_blockdev/base.py:234
#, python-format
msgid "%r is not a valid SI or IEC byte unit."
msgstr "%r ist keine gültige SI- oder IEC-Maßeinheit."

#: pb_blockdev/base.py:592
msgid "No new name given."
msgstr "Kein neuer Name angegeben."

#: pb_blockdev/base.py:597
#, python-format
msgid "Empty name %r given as name of the blockdevice."
msgstr "Leere Name %r als Name des Blockgeräts angegeben."

#: pb_blockdev/base.py:831
#, python-format
msgid "Username %r not found in system."
msgstr "Nutzername %r wurde im System nicht gefunden."

#: pb_blockdev/base.py:835
#, python-format
msgid "Invalid value %r as user id given."
msgstr "Ungültiger Wert %r als Nutzer-Id angegeben."

#: pb_blockdev/base.py:856
#, python-format
msgid "Group name %r not found in system."
msgstr "Der Gruppenname %r wurde im System nicht gefunden."

#: pb_blockdev/base.py:860
#, python-format
msgid "Invalid value %r as group id given."
msgstr "Ungültiger Wert %r als Gruppen-Id angegeben."

#: pb_blockdev/base.py:901 pb_blockdev/devices.py:72 pb_blockdev/dm.py:506 pb_blockdev/loop.py:252
#: pb_blockdev/md/device.py:830 pb_blockdev/multipath/device.py:170 pb_blockdev/scsi.py:573
msgid "No device name given."
msgstr "Kein Gerätename angegeben."

#: pb_blockdev/base.py:903 pb_blockdev/devices.py:74 pb_blockdev/dm.py:508 pb_blockdev/loop.py:254
#: pb_blockdev/md/device.py:832 pb_blockdev/multipath/device.py:172 pb_blockdev/scsi.py:575
#, python-format
msgid "Invalid device name %r given."
msgstr "Ungültiger Gerätename %r angegeben."

#: pb_blockdev/base.py:969
msgid ""
"Cannot retrieve statistics, because it's an unnamed block device object."
msgstr ""
"Kann keine Statistiken ermitteln, weil es ein unbenanntes Blockgeräte-Objekt ist."

#: pb_blockdev/base.py:975
#, python-format
msgid ""
"Cannot retrieve statistics of %r, because the block device doesn't exists."
msgstr ""
"Kann keine Statistiken von %r ermitteln, weil das Blockgerät nicht existiert."

#: pb_blockdev/base.py:983
#, python-format
msgid ""
"Cannot retrieve statistics of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr ""
"Kann keine Statistiken von %(bd)r ermitteln, weil die Datei %(file)r nicht existiert."

#: pb_blockdev/base.py:853
#, python-format
msgid ""
"Cannot retrieve statistics of %(bd)r, because no read access to %(file)r."
msgstr ""
"Kann keine Statistiken von %(bd)r ermitteln, weil keine Leserechte auf die Datei "
"%(file)r vorhanden sind."

#: pb_blockdev/base.py:859
#, python-format
msgid ""
"Cannot retrieve statistics of %(bd)r, because file %(file)r has no content."
msgstr ""
"Kann keine Statistiken von %(bd)r ermitteln, weil die Datei %(file)r "
"keinen Inhalt hat."

#: pb_blockdev/base.py:899
msgid ""
"Cannot retrieve removable state, because it's an unnamed block device object."
msgstr ""
"Kann den removable-Status nicht ermitteln, weil es ein unbenanntes Blockgeräte-Objekt ist."

#: pb_blockdev/base.py:904
#, python-format
msgid ""
"Cannot retrieve removable state of %r, because the block device doesn't "
"exists."
msgstr ""
"Kann den removable-Status von %r nicht ermitteln, weil das Blockgerät nicht existiert."

#: pb_blockdev/base.py:725
#, python-format
msgid ""
"Cannot retrieve removable state of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr ""
"Kann den removable-Status von %(bd)r nicht ermitteln, weil die Datei %(file)r nicht existiert."

#: pb_blockdev/base.py:730
#, python-format
msgid ""
"Cannot retrieve removable state of %(bd)r, because no read access to "
"%(file)r."
msgstr ""
"Kann den removable-Status von %(bd)r nicht ermitteln, weil keine Leserechte auf die Datei "
"%(file)r vorhanden sind."

#: pb_blockdev/base.py:736
#, python-format
msgid ""
"Cannot retrieve removable state of %(bd)r, because file %(file)r has no "
"content."
msgstr ""
"Kann den removable-Status von %(bd)r nicht ermitteln, weil die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/base.py:756
msgid ""
"Cannot retrieve readonly state, because it's an unnamed block device object."
msgstr ""
"Kann den readonly-Status nicht ermitteln, weil es ein unbenanntes Blockgeräte-Objekt ist."

#: pb_blockdev/base.py:760
#, python-format
msgid ""
"Cannot retrieve readonly state of %r, because the block device doesn't "
"exists."
msgstr ""
"Kann den readonly-Status von %r nicht ermitteln, weil das Blockgerät nicht existiert."

#: pb_blockdev/base.py:765
#, python-format
msgid ""
"Cannot retrieve readonly state of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr ""
"Kann den readonly-Status von %(bd)r nicht ermitteln, weil die Datei %(file)r nicht existiert."

#: pb_blockdev/base.py:770
#, python-format
msgid ""
"Cannot retrieve readonly state of %(bd)r, because no read access to %(file)r."
msgstr ""
"Kann den readonly-Status von %(bd)r nicht ermitteln, weil keine Leserechte auf die Datei "
"%(file)r vorhanden sind."

#: pb_blockdev/base.py:776
#, python-format
msgid ""
"Cannot retrieve readonly state of %(bd)r, because file %(file)r has no "
"content."
msgstr ""
"Kann den readonly-Status von %(bd)r nicht ermitteln, weil die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/base.py:796
msgid "Cannot retrieve size, because it's an unnamed block device object."
msgstr ""
"Kann die Größe nicht ermitteln, weil es ein unbenanntes Blockgeräte-Objekt ist."

#: pb_blockdev/base.py:800
#, python-format
msgid "Cannot retrieve size of %r, because the block device doesn't exists."
msgstr ""
"Kann die Größe von %r nicht ermitteln, weil das Blockgerät nicht existiert."

#: pb_blockdev/base.py:805
#, python-format
msgid ""
"Cannot retrieve size of %(bd)r, because the file %(file)r doesn't exists."
msgstr ""
"Kann die Größe von %(bd)r nicht ermitteln, weil die Datei %(file)r nicht existiert."

#: pb_blockdev/base.py:810
#, python-format
msgid "Cannot retrieve size of %(bd)r, because no read access to %(file)r."
msgstr ""
"Kann die Größe von %(bd)r nicht ermitteln, weil keine Leserechte auf die Datei "
"%(file)r vorhanden sind."

#: pb_blockdev/base.py:816
#, python-format
msgid "Cannot retrieve size of %(bd)r, because file %(file)r has no content."
msgstr ""
"Kann die Größe von %(bd)r nicht ermitteln, weil die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/base.py:823
#, python-format
msgid ""
"Cannot retrieve size of %(bd)r, because file %(file)r has illegal content: "
"%(err)s"
msgstr ""
"Kann die Größe von %(bd)r nicht ermitteln, weil die Datei %(file)r keinen gültigen Inhalt hat: %(err)s"

#: pb_blockdev/base.py:840
msgid ""
"Cannot retrieve major/minor number, because it's an unnamed block device "
"object."
msgstr ""
"Kann die Major/Minor-Nummer nicht ermitteln, weil es ein unbenanntes Blockgeräte-Objekt ist."

#: pb_blockdev/base.py:844
#, python-format
msgid ""
"Cannot retrieve major/minor number of %r, because the block device doesn't "
"exists."
msgstr ""
"Kann die Major/Minor-Nummer von %r nicht ermitteln, weil das Blockgerät nicht existiert."

#: pb_blockdev/base.py:850
#, python-format
msgid ""
"Cannot retrieve major/minor number of %(bd)r, because the file %(file)r "
"doesn't exists."
msgstr ""
"Kann die Major/Minor-Nummer von %(bd)r nicht ermitteln, weil die Datei %(file)r nicht existiert."

#: pb_blockdev/base.py:855
#, python-format
msgid ""
"Cannot retrieve major/minor number of %(bd)r, because no read access to "
"%(file)r."
msgstr ""
"Kann die Major/Minor-Nummer von %(bd)r nicht ermitteln, weil keine Leserechte auf die Datei "
"%(file)r vorhanden sind."

#: pb_blockdev/base.py:861
#, python-format
msgid ""
"Cannot retrieve major/minor number of %(bd)r, because file %(file)r has no "
"content."
msgstr ""
"Kann die Major/Minor-Nummer von %(bd)r nicht ermitteln, weil die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/base.py:867
#, python-format
msgid ""
"Cannot retrieve major/minor number of %(bd)r, because cannot evaluate "
"content of %(file)r: %(cont)r"
msgstr ""
"Kann die Major/Minor-Nummer von %(bd)r nicht ermitteln, weil der Inhalte der Datei %(file)r "
"nicht auswertbar ist:  %(cont)r"

#: pb_blockdev/base.py:891 pb_blockdev/base.py:896
#, python-format
msgid "Block device %r to wipe doesn't exists."
msgstr "Das Blockgerät %r zum kompletten Löschen existiert nicht."

#: pb_blockdev/base.py:901
#, python-format
msgid "Wiping %(dev)r by writing %(count)d blocks of %(bs)s binary zeroes ..."
msgstr "Lösche %(dev)r komplett durch Schreiben von %(count)d Blöcken von %(bs)s binären Nullen ..."

#: pb_blockdev/base.py:1268
#, python-format
msgid "Writing %(count)d blocks of %(bs)s binary zeroes into %(dev)r ..."
msgstr "Schreibe %(count)d Blöcke von %(bs)s binären Nullen nach %(dev)r ..."

#: pb_blockdev/base.py:1138 pb_blockdev/base.py:1142
#, python-format
msgid "No %s number for mknod given."
msgstr "Keine %s-Nummer für mknod angegeben."

#: pb_blockdev/base.py:1156
#, python-format
msgid "Device file %r already exists."
msgstr "Gerätedatei %r existiert bereits."

#: pb_blockdev/base.py:1159
#, python-format
msgid "Device file %r is not a block device file."
msgstr "Gerätedatei %r ist keine Blockgeräte-Datei."

#: pb_blockdev/base.py:1164
#, python-format
msgid "Wrong block device %r: "
msgstr "Falsches Blockgerät %r: "

#: pb_blockdev/base.py:1165
#, python-format
msgid "it has a major:minor number of %(mje)d:%(mne)d instead of %(mjs)d:%(mns)d."
msgstr "es hat eine Major:Minor-Nummer von %(mje)d:%(mne)d anstatt von %(mjs)d:%(mns)d."

#: pb_blockdev/base.py:1172
#, python-format
msgid "Creating block device file %(dev)r with mode %(mod)o ..."
msgstr "Erstelle Blockgeräte-Datei %(dev)r mit Dateimodus %(mod)o ..."

#: pb_blockdev/base.py:1175
#, python-format
msgid "Chowning block device file %(dev)r to UID %(u)d and GID %(g)d."
msgstr "Schenke Blockgeräte-Datei %(dev)r an UID %(u)d und GID %(g)d."

#: pb_blockdev/base.py:1454
#, python-format
msgid "Invalid mode %r given."
msgstr "Ungültiger Modus %r angegeben."

#: pb_blockdev/base.py:1458
#, python-format
msgid "Opening %(d)r with mode %(m)r (buffering: %(b)d)."
msgstr "Öffne %(d)r im Modus %(m)r (Pufferung: %(b)d)."

#: pb_blockdev/base.py:1462
msgid "Blockdevice does not exists."
msgstr "Das Blockgerät existiert nicht."

#: pb_blockdev/base.py:1483
#, python-format
msgid "Trying to flush buffers of a non-existing device %r."
msgstr "Versuch, die Puffer des nicht existierenden Geräts %r zu leeren."

#: pb_blockdev/base.py:1488
#, python-format
msgid "Cannot flush buffers of device %r, device is readonly."
msgstr "Kann Puffer von Gerät %r nicht leeren, das Gerät ist schreibseschützt."

#: pb_blockdev/base.py:1493
#, python-format
msgid "Cannot flush buffers of device %(d)r, command %(c)r not found."
msgstr "Konnte Puffer von Gerät %(d)r nicht leeren, das Kommando %(c)r wurde nicht gefunden."

#: pb_blockdev/base.py:1507
#, python-format
msgid "Flushing buffers of device %r ..."
msgstr "Leere Puffer von Gerät %r ..."

#: pb_blockdev/base.py:1381
msgid "Empty path to check with fuser given."
msgstr "Leerer Pfad zur Überprüfung mit fuser angegeben."

#: pb_blockdev/base.py:1385
#, python-format
msgid "Checking existence of %r ..."
msgstr "Überprüfe Existenz von %r ..."

#: pb_blockdev/base.py:1509 pb_blockdev/base.py:1567 pb_blockdev/lvm/__init__.py:377
#: pb_blockdev/md/__init__.py:448 pb_blockdev/multipath/__init__.py:211
msgid "Executing as root:"
msgstr "Führe als root aus:"

#: pb_blockdev/base.py:1511 pb_blockdev/base.py:1569 pb_blockdev/lvm/__init__.py:379
#: pb_blockdev/md/__init__.py:451 pb_blockdev/multipath/__init__.py:213
msgid "Executing:"
msgstr "Führe aus:"

#: pb_blockdev/base.py:1409
#, python-format
msgid "Path %r is not used by any process."
msgstr "Der Pfad %r wird von keinem Prozess verwendet."

#: pb_blockdev/base.py:1517
#, python-format
msgid "Error %(n)d executing \"%(c)s\": %(e)s"
msgstr "Fehler %(n)d bei der Ausführung von\"%(c)s\": %(e)s"

#: pb_blockdev/base.py:1521
#, python-format
msgid "Flushing buffers of device %r successful."
msgstr "Das Leeren der Puffer von Gerät %r war erfolgreich."

#: pb_blockdev/base.py:1412
#, python-format
msgid "Error on executing \"%(cmd)s\": %(err)s"
msgstr "Fehler bei der Ausführung von\"%(cmd)s\": %(err)s"

#: pb_blockdev/base.py:1439
#, python-format
msgid "Checking, whether %r is opened by processes ..."
msgstr "Überprüfe, ob %r von einem Prozess geöffnet ist ..."

#: pb_blockdev/base.py:1446
#, python-format
msgid "Checking, whether %r has holder devices ..."
msgstr "Überprüfe, ob %r Holder-Geräte besitzt ..."

#: pb_blockdev/base.py:1518
#, python-format
msgid "%s does not support deletion of the device."
msgstr "%s unterstützt kein Löschen des Geräts."

#: pb_blockdev/disk.py:102
msgid "Unknown disk"
msgstr "Unbekannte Platte"

#: pb_blockdev/disk.py:108
msgid "Unknown reason"
msgstr "Unbekannter Grund"

#: pb_blockdev/disk.py:113
#, python-format
msgid "Could not discover disk %r:"
msgstr "Konnte Disk %r nicht erforschen:"

#: pb_blockdev/disk.py:420
#, python-format
msgid "Disk %r is even discovered."
msgstr "Disk %r wurde bereits erforscht."

#: pb_blockdev/disk.py:427 pb_blockdev/scsi.py:919
#, python-format
msgid "Directory %r doesn't exists."
msgstr "Das Verzeichnis %r existiert nicht."

#: pb_blockdev/disk.py:429
#, python-format
msgid "Discovery of disk %r ..."
msgstr "Erforschung von Disk %r ..."

#: pb_blockdev/dm.py:96
#, python-format
msgid "Error %(errno)d suspending device mapper device %(dev)r: %(msg)s"
msgstr "Fehler %(errno)d beim Unterbrechen des Devicemapper-Geräts %(dev)r: %(msg)s"

#: pb_blockdev/dm.py:130
#, python-format
msgid "Error %(errno)d resuming device mapper device %(dev)r: %(msg)s"
msgstr "Fehler %(errno)d beim Fortsetzen des Devicemapper-Geräts %(dev)r: %(msg)s"

#: pb_blockdev/dm.py:163
#, python-format
msgid "Error %(errno)d getting device mapper table of device %(dev)r: %(msg)s"
msgstr "Fehler %(errno)d beim Ermitteln der Devicemapper-Tabelle des Geräts %(dev)r: %(msg)s"

#: pb_blockdev/dm.py:199
#, python-format
msgid ""
"Error %(errno)d setting device mapper table %(tbl)r of device %(dev)r: "
"%(msg)s"
msgstr "Fehler %(errno)d beim Setzen der Devicemapper-Tabelle %(tbl)r des Geräts %(dev)r: %(msg)s"

#: pb_blockdev/dm.py:229 pb_blockdev/dm.py:266
msgid "Unknown error"
msgstr "Unbekannter Fehler"

#: pb_blockdev/dm.py:237
#, python-format
msgid "Error removing device mapper device %(dev)r: %(msg)s"
msgstr "Fehler beim Löschen des Devicemapper-Geräts %(dev)r: %(msg)s"

#: pb_blockdev/dm.py:274
#, python-format
msgid "Error creating device mapper device %(dev)r: %(msg)s"
msgstr "Fehler beim Erstellen des Devicemapper-Geräts %(dev)r: %(msg)s"

#: pb_blockdev/dm.py:334
#, python-format
msgid ""
"In minimum one parameter of 'name' and 'dm_name' must be given on "
"initialisation of a %s."
msgstr ""
"Mindestens einer der Parameter 'name' oder 'dm_name' muss bei der Initialisierung "
"eines %s-Objektes angegeben werden."

#: pb_blockdev/dm.py:395 pb_blockdev/loop.py:142
msgid "Initialized."
msgstr "Initialisiert."

#: pb_blockdev/dm.py:555
#, python-format
msgid "Base device dir of device mapper %r doesn't exists."
msgstr "Basis-Geräteverzeichnis de Devicemappers %r existiert nicht."

#: pb_blockdev/dm.py:571
#, python-format
msgid "Could not extract blockdevice name from %r."
msgstr "Konnte den Namen des Blockgerätes nicht aus %r ermitteln."

#: pb_blockdev/dm.py:575
#, python-format
msgid "Checking blockdevice %r for DM name ..."
msgstr "Überprüfe Blockgerät %r für den Devicemapper-Namen ..."

#: pb_blockdev/dm.py:578
#, python-format
msgid "Cannot retrieve name from of %r, because of no read access."
msgstr "Konnte den Namen nicht aus %r ermitteln, da keine Leserechte vorhanden sind."

#: pb_blockdev/dm.py:584
#, python-format
msgid "Cannot retrieve name from %r, because file has no content."
msgstr "Konnte den Namen nicht aus %r ermitteln, da die Datei keinen Inhalt hat."

#: pb_blockdev/dm.py:592
#, python-format
msgid "Could not retrieve blockdevice name for DM name %r."
msgstr "Konnte den Namen des Blockgerätes für den Devicemapper-Namen %r nicht ermitteln."

#: pb_blockdev/dm.py:608
msgid ""
"Cannot retrieve dm_name file, because it's an unnamed devicemapper device "
"object."
msgstr "Konnte die 'dm_name'-Datei nicht ermitteln, weil es ein unbenanntes "
"Devicemapper-Geräte-Objekt ist."

#: pb_blockdev/dm.py:612
#, python-format
msgid ""
"Cannot retrieve dm_name file of %r, because the devicemapper device doesn't "
"exists."
msgstr ""
"Konnte die 'dm_name'-Datei von %r nicht ermitteln, weil das Devicemapper-Gerät "
"nicht existiert."

#: pb_blockdev/dm.py:618
#, python-format
msgid ""
"Cannot retrieve dm_name file of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr ""
"Konnte die 'dm_name'-Datei von %(bd)r nicht ermitteln, weil die Datei %(file)r "
"nicht existiert."

#: pb_blockdev/dm.py:623
#, python-format
msgid ""
"Cannot retrieve dm_name file of %(bd)r, because no read access to %(file)r."
msgstr ""
"Konnte die 'dm_name'-Datei von %(bd)r nicht ermitteln, da keine Leserechte "
"auf die Datei %(file)r vorhanden sind."

#: pb_blockdev/dm.py:629
#, python-format
msgid ""
"Cannot retrieve dm_name file of %(bd)r, because file %(file)r has no content."
msgstr ""
"Konnte die 'dm_name'-Datei von %(bd)r nicht ermitteln, da die Datei "
"%(file)r keinen Inhalt hat."

#: pb_blockdev/dm.py:646
msgid ""
"Cannot retrieve suspended state, because it's an unnamed devicemapper device "
"object."
msgstr ""
"Kann den suspended-Status nicht ermitteln, weil es ein unbenanntes "
"Devicemapper-Geräte-Objekt ist."

#: pb_blockdev/dm.py:650
#, python-format
msgid ""
"Cannot retrieve suspended state of %r, because the devicemapper device "
"doesn't exists."
msgstr ""
"Kann den suspended-Status von %r nicht ermitteln, weil das Devicemapper-Gerät "
"nicht existiert."

#: pb_blockdev/dm.py:656
#, python-format
msgid ""
"Cannot retrieve suspended state of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr ""
"Kann den suspended-Status von %(bd)r nicht ermitteln, weil die Datei "
"%(file)r nicht existiert."

#: pb_blockdev/dm.py:661
#, python-format
msgid ""
"Cannot retrieve suspended state of %(bd)r, because no read access to "
"%(file)r."
msgstr ""
"Kann den suspended-Status von %(bd)r nicht ermitteln, weil keine Leserechte auf die "
"Datei %(file)r vorhanden sind."

#: pb_blockdev/dm.py:667
#, python-format
msgid ""
"Cannot retrieve suspended state of %(bd)r, because file %(file)r has no "
"content."
msgstr ""
"Kann den suspended-Status von %(bd)r nicht ermitteln, weil die Datei "
"%(file)r keinen Inhalt hat."

#: pb_blockdev/dm.py:687
msgid ""
"Cannot retrieve UUID, because it's an unnamed devicemapper device object."
msgstr ""
"Kann die UUID nicht ermitteln, weil es ein unbenanntes "
"Devicemapper-Geräte-Objekt ist."

#: pb_blockdev/dm.py:691
#, python-format
msgid ""
"Cannot retrieve UUID of %r, because the devicemapper device doesn't exists."
msgstr ""
"Kann die UUID von %r nicht ermitteln, weil das Devicemapper-Gerät "
"nicht existiert."

#: pb_blockdev/dm.py:697
#, python-format
msgid ""
"Cannot retrieve UUID of %(bd)r, because the file %(file)r doesn't exists."
msgstr ""
"Kann die UUID von %(bd)r nicht ermitteln, weil die Datei "
"%(file)r nicht existiert."

#: pb_blockdev/dm.py:702
#, python-format
msgid "Cannot retrieve UUID of %(bd)r, because no read access to %(file)r."
msgstr ""
"Kann die UUID von %(bd)r nicht ermitteln, weil keine Leserechte auf die "
"Datei %(file)r vorhanden sind."

#: pb_blockdev/dm.py:733
msgid "Cannot retrieve DM table, because I have no name."
msgstr "Kann die Devicemapper-Tabelle nicht ermitteln, weil ich keinen Namen habe."

#: pb_blockdev/dm.py:737
#, python-format
msgid "Trying to get current device mapper table of %r ..."
msgstr "Versuche, die aktuelle Devicemapper-Tabelle von %r zu ermitteln ..."

#: pb_blockdev/dm.py:752
#, python-format
msgid "Device %r has an empty DM table."
msgstr "Das Gerät %r hat eine leere Devicemapper-Tabelle."

#: pb_blockdev/dm.py:768
#, python-format
msgid "Suspending DM device %r ..."
msgstr "Unterbreche Devicemapper-Gerät %r ..."

#: pb_blockdev/dm.py:782
#, python-format
msgid ""
"DM device %r is not suspended yet, but it should so. Waiting a minimal "
"time ..."
msgstr ""
"Das Devicemapper-Gerät %r ist noch nicht unterbrochen, sollte es aber sein. "
"Warte einen kleinen Moment ..."

#: pb_blockdev/dm.py:791
#, python-format
msgid "not suspended after %0.3f seconds, but it should so"
msgstr "nicht nach %0.3f Sekunden unterbrochen, aber sollte so sein"

#: pb_blockdev/dm.py:795
#, python-format
msgid "DM device %(dev)r suspended in %(sec)0.3f seconds."
msgstr "DM-Gerät %(dev)r nach %(sec)0.3f Sekunden unterbrochen."

#: pb_blockdev/dm.py:809
#, python-format
msgid "Resuming DM device %r ..."
msgstr "DM-Gerät %r wieder fortgesetzt ..."

#: pb_blockdev/dm.py:823
#, python-format
msgid ""
"DM device %r is not resumed yet, but it should so. Waiting a minimal time ..."
msgstr ""
"Das DM-Gerät %r hat noch nicht fortgesetzt, sollte aber bereits. "
"Warte einen kleinen Zeitraum ..."

#: pb_blockdev/dm.py:832
#, python-format
msgid "not resumed after %0.3f seconds, but it should so"
msgstr "nach %0.3f nicht fortgesetzt, aber das sollte es"

#: pb_blockdev/dm.py:836
#, python-format
msgid "DM device %(dev)r resumed in %(sec)0.3f seconds."
msgstr "DM-Gerät %(dev)r nach %(sec)0.3f Sekunden fortgesetzt."

#: pb_blockdev/dm.py:859
#, python-format
msgid ""
"Force switch is set, trying to remove device mapper device %r anyhow ..."
msgstr "Zwangs-Schalter wurde angegeben, versuche das DM-Gerät %r irgendwie zu entfernen ..."

#: pb_blockdev/dm.py:870
#, python-format
msgid "Removing devicemapper device %r FORCED ..."
msgstr "Entferne Devicemapper-Gerät %r PER ZWANG ..."

#: pb_blockdev/dm.py:873
#, python-format
msgid "Removing devicemapper device %r ..."
msgstr "Entferne Devicemapper-Gerät %r ..."

#: pb_blockdev/dm.py:883
#, python-format
msgid "error %d: "
msgstr "Fehler %d: "

#: pb_blockdev/dm.py:892
#, python-format
msgid ""
"DM device %r is not removed yet, but it should so. Waiting a minimal time ..."
msgstr "DM-Gerät %r ist noch nicht entfernt, aber das sollte es. Warte einen Augenblick ..."

#: pb_blockdev/dm.py:900
#, python-format
msgid "not removed after %0.1f seconds, but it should so"
msgstr "nach %0.1f Sekunden nicht entfernt, aber das sollte es"

#: pb_blockdev/dm.py:904
#, python-format
msgid "DM device %(dev)r removed in %(sec)0.3f seconds."
msgstr " Devicemapper-Gerät %(dev)r in %(sec)0.3f Sekunden entfernt."

#: pb_blockdev/hbtl.py:75 pb_blockdev/hbtl.py:81 pb_blockdev/hbtl.py:87
#: pb_blockdev/hbtl.py:93
#, python-format
msgid "Invalid value %(val)r for %(what)r."
msgstr "Ungültiger Wert %(val)r für %(what)r."

#: pb_blockdev/hbtl.py:161
#, python-format
msgid "Could not interprete %r as a SCSI HBTL address."
msgstr "Konnte %r nicht als SCSI HBTL Adresse interpretieren."

#: pb_blockdev/hbtl.py:199
#, python-format
msgid "Comparision partner %r is not a HBTL object."
msgstr "Der Vergleichspartner %r ist kein HBTL-Objekt."

#: pb_blockdev/loop.py:273 pb_blockdev/scsi.py:572 pb_blockdev/scsi.py:579
#, python-format
msgid "No read access to %r."
msgstr "Kein Lesezugriff auf %r."

#: pb_blockdev/loop.py:321
msgid ""
"Cannot retrieve backing file, because it's an unnamed loop device object."
msgstr "Kann Image-Datei nicht ermitteln, da es ein unbenanntes Loop-Geräteobjekt ist."

#: pb_blockdev/loop.py:325
#, python-format
msgid ""
"Cannot retrieve backing file of %r, because the loop device doesn't exists."
msgstr "Kann Image-Datei von %r nicht ermitteln, da das Loop-Gerät nicht existiert."

#: pb_blockdev/loop.py:330
#, python-format
msgid ""
"Cannot retrieve backing file of %r, because the loop device isn't attached."
msgstr "Kann Image-Datei von %r nicht ermitteln, da das Loop-Gerät nicht zugeordnet ist."

#: pb_blockdev/loop.py:336
#, python-format
msgid ""
"Cannot retrieve backing file of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann Image-Datei von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/loop.py:341
#, python-format
msgid ""
"Cannot retrieve backing file of %(bd)r, because no read access to %(file)r."
msgstr "Kann Image-Datei von %(bd)r nicht ermitteln, da keine Leserechte auf %(file)r bestehen."

#: pb_blockdev/loop.py:347
#, python-format
msgid ""
"Cannot retrieve backing file of %(bd)r, because file %(file)r has no content."
msgstr "Kann Image-Datei von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/loop.py:364
msgid "Cannot retrieve offset, because it's an unnamed loop device object."
msgstr "Kann Offset nicht ermitteln, da es ein unbenanntes Loop-Geräteobjekt ist."

#: pb_blockdev/loop.py:368
#, python-format
msgid "Cannot retrieve offset of %r, because the loop device doesn't exists."
msgstr "Kann Offset von %r nicht ermitteln, da das Loop-Gerät nicht existiert."

#: pb_blockdev/loop.py:373
#, python-format
msgid "Cannot retrieve offset of %r, because the loop device isn't attached."
msgstr "Kann Offset von %r nicht ermitteln, da das Loop-Gerät nicht zugeordnet ist."

#: pb_blockdev/loop.py:379
#, python-format
msgid ""
"Cannot retrieve offset of %(bd)r, because the file %(file)r doesn't exists."
msgstr "Kann Offset von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/loop.py:384
#, python-format
msgid "Cannot retrieve offset of %(bd)r, because no read access to %(file)r."
msgstr "Kann Offset von %(bd)r nicht ermitteln, da keine Leserechte auf %(file)r bestehen."

#: pb_blockdev/loop.py:390
#, python-format
msgid "Cannot retrieve offset of %(bd)r, because file %(file)r has no content."
msgstr "Kann Offset von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/loop.py:397
#, python-format
msgid ""
"Cannot retrieve offset of %(bd)r, because file %(file)r has illegal content: "
"%(err)s"
msgstr "Kann Offset von %(bd)r nicht ermitteln, da die Datei %(file)r einen ungültigen Inhalt hat: %(err)s"

#: pb_blockdev/loop.py:412
msgid "Cannot retrieve sizelimit, because it's an unnamed loop device object."
msgstr "Kann Größenbegrenzung nicht ermitteln, da es ein unbenanntes Loop-Geräteobjekt ist."

#: pb_blockdev/loop.py:416
#, python-format
msgid ""
"Cannot retrieve sizelimit of %r, because the loop device doesn't exists."
msgstr "Kann Größenbegrenzung von %r nicht ermitteln, da das Loop-Gerät nicht existiert."

#: pb_blockdev/loop.py:421
#, python-format
msgid ""
"Cannot retrieve sizelimit of %r, because the loop device isn't attached."
msgstr "Kann Größenbegrenzung von %r nicht ermitteln, da das Loop-Gerät nicht zugeordnet ist."

#: pb_blockdev/loop.py:427
#, python-format
msgid ""
"Cannot retrieve sizelimit of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann Größenbegrenzung von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/loop.py:432
#, python-format
msgid ""
"Cannot retrieve sizelimit of %(bd)r, because no read access to %(file)r."
msgstr "Kann Größenbegrenzung von %(bd)r nicht ermitteln, da keine Leserechte auf %(file)r bestehen."

#: pb_blockdev/loop.py:438
#, python-format
msgid ""
"Cannot retrieve sizelimit of %(bd)r, because file %(file)r has no content."
msgstr "Kann Größenbegrenzung von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/loop.py:445
#, python-format
msgid ""
"Cannot retrieve sizelimit of %(bd)r, because file %(file)r has illegal "
"content: %(err)s"
msgstr "Kann Größenbegrenzung von %(bd)r nicht ermitteln, da die Datei %(file)r "
"einen ungültigen Inhalt hat: %(err)s"

#: pb_blockdev/loop.py:474
#, python-format
msgid ""
"The current loop device %(lo)r is even attached to the backing file "
"%(bfile)r."
msgstr "Das aktuelle Loop-Gerät %(lo)r ist bereits der Image-Datei %(bfile)r zugeordnet."

#: pb_blockdev/loop.py:479
msgid "No filename given onn calling attach()."
msgstr "Kein Dateiname beim Aufruf von attach() angegeben."

#: pb_blockdev/loop.py:485
#, python-format
msgid "File %r doesn't exists."
msgstr "Die Datei %r existiert nicht."

#: pb_blockdev/loop.py:489
#, python-format
msgid "File %r exists, but is not a regular file."
msgstr "Die Date %r existiert zwar, ist aber keine reguläre Datei."

#: pb_blockdev/loop.py:493
#, python-format
msgid "Attaching %(file)r to loop device %(dev)s ..."
msgstr "Ordne Datei %(file)r zu Loop-Gerät %(dev)s zu ..."

#: pb_blockdev/loop.py:496
#, python-format
msgid "Attaching %r to a loop device ..."
msgstr "Ordne %r einem Loop-Gerät zu ..."

#: pb_blockdev/loop.py:526 pb_blockdev/loop.py:589
msgid "undefined error"
msgstr "nicht definierter Fehler"

#: pb_blockdev/loop.py:531
#, python-format
msgid "Error %(no)d on attaching %(file)r with losetup: %(msg)s"
msgstr "Fehler %(no)d beim Zuordnen von %(file)r mit losetup: %(msg)s"

#: pb_blockdev/loop.py:536
#, python-format
msgid "Trying to get the new device name from %r ..."
msgstr "Versuche, den neuen Gerätenamen von %r zu ermitten ..."

#: pb_blockdev/loop.py:540
#, python-format
msgid "Somehow I could not retrieve the new loop device name from %r."
msgstr "Konnte irgendwie den neuen Gerätenamen von %r nicht ermitteln."

#: pb_blockdev/loop.py:543
#, python-format
msgid "Used loop device for attaching: %r"
msgstr "Verwendetes Loop-Gerät für Zuordnung: %r"

#: pb_blockdev/loop.py:545
#, python-format
msgid ""
"Got %(lo)r as a new loop device name, but %(dir)s doesn't seems to exist."
msgstr "Habe %(lo)r als neuen Loop-Gerätenamen erhalten, aber %(dir)s scheint nicht zu existieren."

#: pb_blockdev/loop.py:550
#, python-format
msgid ""
"Loop device %(lo)r was attached to %(file)r, but %(dir)s doesn't seems to "
"exist."
msgstr "Loop-Gerät %(lo)r wurde %(file)r zugeordnet, aber %(dir)s scheint nicht zu existieren."

#: pb_blockdev/loop.py:570
#, python-format
msgid "Device %r is even detached from some backing file."
msgstr "Gerät %r ist bereits von einer Image-Datei getrennt."

#: pb_blockdev/loop.py:577
#, python-format
msgid "Detaching loop device %s ..."
msgstr "Trenne Loop-Gerät %s ..."

#: pb_blockdev/loop.py:594
#, python-format
msgid "Error %(no)d on detaching %(dev)r with losetup: %(msg)s"
msgstr "Fehler %(no)d bein Trenne von %(dev)r mit losetup: %(msg)s"

#: pb_blockdev/lvm/__init__.py:356
#, python-format
msgid "No arguments given on calling %s()."
msgstr "Keine Argumente beim Aufruf von %s() angegeben."

#: pb_blockdev/lvm/__init__.py:402 pb_blockdev/md/__init__.py:474
#, python-format
msgid "Timeout on executing: %d second."
msgstr "Zeitüberschreitung bei der Ausführung: %d Sekunden."

#: pb_blockdev/lvm/__init__.py:413 pb_blockdev/md/__init__.py:484
#: pb_blockdev/multipath/__init__.py:225
#, python-format
msgid "Error %(rc)d executing \"%(cmd)s\": %(msg)s"
msgstr "Fehler %(rc)d bei der Ausführung von \"%(cmd)s\": %(msg)s"

#: pb_blockdev/lvm/volume.py:404
#, python-format
msgid "No device path for %(class)s %(name)r defined."
msgstr "Kein Device-Pfad für %(class)s %(name)r definiert."

#: pb_blockdev/lvm/volume.py:423 pb_blockdev/lvm/volume.py:470
#, python-format
msgid "Method %(method)s() of object %(class)s must be overwritten!"
msgstr "Die Methode %(method)s() von Objekt %(class)s muß überschrieben werden!"

#: pb_blockdev/md/__init__.py:164
#, python-format
msgid "Timeout on executing %r."
msgstr "Zeitüberschreitung bei der Ausführung von %r."

#: pb_blockdev/md/__init__.py:167 pb_blockdev/md/admin.py:119
#, python-format
msgid " (timeout after %0.1f secs)"
msgstr " (Zeitüberschreitung nach %0.1f Sekunden)"

#: pb_blockdev/md/__init__.py:322
#, python-format
msgid "A timeout must be greater than zero (not %d)."
msgstr "Ein Timeout muss größer als Null sein (nicht %d)."

#: pb_blockdev/md/__init.py:291
#, python-format
msgid "Global lockfile %r already occupied."
msgstr "Globale Lockdatei %r bereits belegt."

#: pb_blockdev/md/__init.py:340
msgid "No arguments given on calling exec_mdadm()."
msgstr "Keine Argumente beim Aufruf von exec_mdadm() übergeben."

#: pb_blockdev/md/__init.py:344
#, python-format
msgid "Invalid mode %r on calling exec_mdadm() given."
msgstr "Ungültiger Modus %r beim Aufruf von exec_mdadm() angegeben."

#: pb_blockdev/md/admin.py:116
msgid "Timeout on dumping"
msgstr "Zeitüberschreitung beim Dumpen"

#: pb_blockdev/md/admin.py:500
#, python-format
msgid "Regex to analyze output of %(w)r:"
msgstr "Regulärer Ausdruck zur Analyse des Ausgabe von %(w)r:"

#: pb_blockdev/md/admin.py:254
#, python-format
msgid "Maximum MD ID of %d reached."
msgstr "Maximale MD ID von %d erreicht."

#: pb_blockdev/md/admin.py:291
#, python-format
msgid "Parameter %(p)r must be of type %(t)r, but is of type %(i)r instead."
msgstr "Der Parameter %(p)r muss vom Typ %(t)r sein, ist aber statt dessen vom Typ %(i)r."

#: pb_blockdev/md/admin.py:296
#, python-format
msgid "Device %r does not exist."
msgstr "Das Gerät %r existiert nicht."

#. Execute 'mdadm --zero-superblock --force'
#: pb_blockdev/md/admin.py:300
#, python-format
msgid "Zeroing MD superblock on device %r."
msgstr "Nulle den MD Superblock von Gerät %r."

#: pb_blockdev/md/admin.py:839
#, python-format
msgid "Dumping %(d)r, timeout %(t)d second."
msgstr "Dumpe %(d)r, Zeitüberschreitung nach %(t)d Sekunden."

#: pb_blockdev/md/admin.py:876 pb_blockdev/md/device.py:1238
#, python-format
msgid "Cannot examine %r, because it does not exists."
msgstr "Kann %r nicht untersuchen, da es nicht existiert."

#: pb_blockdev/md/admin.py:886
#, python-format
msgid "Examining MD superblock on %r ..."
msgstr "Untersuche MD Superblock von %r ..."

#: pb_blockdev/md/admin.py:892
#, python-format
msgid "No MD superblock on %(d)r found: %(m)s"
msgstr "Kein MD Superblock auf %(d)r gefunden: %(m)s"

#: pb_blockdev/md/device.py:233
#, python-format
msgid "Cannot retrieve slot number, because the file %(file)r doesn't exists."
msgstr "Kann Slotnummer nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:240
#, python-format
msgid "Cannot retrieve slot number, because no read access to %(file)r."
msgstr "Kann Slotnummer nicht ermitteln, da die Datei %(file)r nicht gelesen werden darf."

#: pb_blockdev/md/device.py:246
#, python-format
msgid "Retrieving slot of MD sub device from %r ..."
msgstr "Ermittle Slotnummer von MD Untergerät von %r ..."

#: pb_blockdev/md/device.py:252
#, python-format
msgid "Cannot retrieve slot number, because file %(file)r has no content."
msgstr "Kann Slotnummer nicht ermitteln, da die Datei %(file)r keinen Inhalt aufweist."

#: pb_blockdev/md/device.py:272
#, python-format
msgid "Cannot retrieve state of MD sub device, because the file %(file)r doesn't exists."
msgstr "Kann den Status des MD Untergeräts nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:279
#, python-format
msgid "Cannot retrieve state of MD sub device, because no read access to %(file)r."
msgstr "Kann den Status des MD Untergeräts nicht ermitteln, da die Datei %(file)r nicht gelesen werden darf."

#: pb_blockdev/md/device.py:285
#, python-format
msgid "Retrieving state of MD sub device from %r ..."
msgstr "Ermittle Status des MD Untergeräts aus %r ..."

#: pb_blockdev/md/device.py:291
#, python-format
msgid "Cannot retrieve state of MD sub device, because file %(file)r has no content."
msgstr "Kann den Status des MD Untergeräts nicht ermitteln, da die Datei %(file)r keinen Inhalt aufweist."

#: pb_blockdev/md/device.py:317
msgid "Could not detect underlaying block device, because no sub device dir given."
msgstr "Kann das darunterliegende Blockgerät nicht ermitteln, da kein Verzeichnis für das MD Untergerät angegeben wurde."

#: pb_blockdev/md/device.py:323
#, python-format
msgid "Could not detect underlaying block device, because directory %r does not exists."
msgstr "Konnte das darunterliegende Blockgerät nicht ermitteln, da das Verzeichnis %r nicht existiert."

#: pb_blockdev/md/device.py:330
#, python-format
msgid "Could not detect underlaying block device, because symlink %r does not exists."
msgstr "Konnte das darunterliegende Blockgerät nicht ermitteln, da die symbolische Verknüpfung %r  nicht existiert."

#: pb_blockdev/md/device.py:335
#, python-format
msgid "Could not detect underlaying block device, because %r is not a symbolic link."
msgstr "Konnte das darunterliegende Blockgerät nicht ermitteln, da %r keine symbolische Verknüpfung ist."

#: pb_blockdev/md/device.py:423
#, python-format
msgid "Invalid name %r of a MD device given."
msgstr "Ungültiger Name %r für ein MD Gerät angegeben."

#: pb_blockdev/md/device.py:891
msgid "Cannot retrieve RAID level, because it's an unnamed MD device object."
msgstr "Konnte RAID-Level nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:896
#, python-format
msgid "Cannot retrieve RAID level of %r, because the MD device doesn't exists."
msgstr "Konnte RAID-Level von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:903
#, python-format
msgid "Cannot retrieve RAID level of %(bd)r, because the file %(file)r doesn't exists."
msgstr "Konnte RAID-Level von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:910
#, python-format
msgid "Cannot retrieve RAID level of %(bd)r, because no read access to %(file)r."
msgstr "Konnte RAID-Level von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/md/device.py:918
#, python-format
msgid "Cannot retrieve RAID level of %(bd)r, because file %(file)r has no content."
msgstr "Konnte RAID-Level von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt aufweist."

#: pb_blockdev/md/device.py:937
msgid "Cannot retrieve metadata version, because it's an unnamed MD device object."
msgstr "Konnte Metadaten nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:943
#, python-format
msgid "Cannot retrieve metadata version of %r, because the MD device doesn't exists."
msgstr "Konnte Metadaten von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:950
#, python-format
msgid "Cannot retrieve metadata version of %(bd)r, because the file %(file)r doesn't exists."
msgstr "Konnte Metadaten von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:957
#, python-format
msgid "Cannot retrieve metadata version of %(bd)r, because no read access to %(file)r."
msgstr "Konnte Metadaten von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/md/device.py:965
#, python-format
msgid "Cannot retrieve metadata version of %(bd)r, because file %(file)r has no content."
msgstr "Konnte Metadaten von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt aufweist."

#: pb_blockdev/md/device.py:984
msgid "Cannot retrieve chunk size, because it's an unnamed MD device object."
msgstr "Konnte Datenblockgröße nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:990
#, python-format
msgid "Cannot retrieve chunk size of %r, because the MD device doesn't exists."
msgstr "Konnte Datenblockgröße von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:997
#, python-format
msgid "Cannot retrieve chunk size of %(bd)r, because the file %(file)r doesn't exists."
msgstr "Konnte Datenblockgröße von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:1004
#, python-format
msgid "Cannot retrieve chunk size of %(bd)r, because no read access to %(file)r."
msgstr "Konnte Datenblockgröße von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/md/device.py:1012
#, python-format
msgid "Cannot retrieve chunk size of %(bd)r, because file %(file)r has no content."
msgstr "Konnte Datenblockgröße von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt aufweist."

#: pb_blockdev/md/device.py:1031
msgid "Cannot retrieve state, because it's an unnamed MD device object."
msgstr "Konnte den Status nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:1037
#, python-format
msgid "Cannot retrieve state of %r, because the MD device doesn't exists."
msgstr "Konnte den Status von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:1044
#, python-format
msgid "Cannot retrieve state of %(bd)r, because the file %(file)r doesn't exists."
msgstr "Konnte den Status von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:1051 pb_blockdev/scsi.py:450
#, python-format
msgid "Cannot retrieve state of %(bd)r, because no read access to %(file)r."
msgstr "Kann den Status von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/md/device.py:1059 pb_blockdev/scsi.py:462
#, python-format
msgid "Cannot retrieve state of %(bd)r, because file %(file)r has no content."
msgstr "Kann Status von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1078
msgid "Cannot retrieve degraded state, because it's an unnamed MD device object."
msgstr "Konnte den Status der Einschränkung nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:1084
#, python-format
msgid "Cannot retrieve degraded state of %r, because the MD device doesn't exists."
msgstr "Konnte den Status der Einschränkung von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:1091
#, python-format
msgid "Cannot retrieve degraded state of %(bd)r, because the file %(file)r doesn't exists."
msgstr "Konnte den Status der Einschränkung von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:1101
#, python-format
msgid "Cannot retrieve degraded state of %(bd)r, because no read access to %(file)r."
msgstr "Konnte den Status der Einschränkung von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/md/device.py:1109
#, python-format
msgid "Cannot retrieve degraded state of %(bd)r, because file %(file)r has no content."
msgstr "Konnte den Status der Einschränkung von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1130
msgid "Cannot retrieve the number of raid disks, because it's an unnamed MD device object."
msgstr "Konnte die Anzahl der RAID-Platten nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:1136
#, python-format
msgid "Cannot retrieve the number of raid disks of %r, because the MD device doesn't exists."
msgstr "Konnte die Anzahl der RAID-Platten von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:1143
#, python-format
msgid "Cannot retrieve the number of raid disks of %(bd)r, because the file %(file)r doesn't "
      "exists."
msgstr "Konnte die Anzahl der RAID-Platten von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/md/device.py:1150
#, python-format
msgid "Cannot retrieve the number of raid disks of %(bd)r, because no read access to %(file)r."
msgstr "Konnte die Anzahl der RAID-Platten von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/md/device.py:1158
#, python-format
msgid "Cannot retrieve the number of raid disks of %(bd)r, because file %(file)r has no content."
msgstr "Konnte die Anzahl der RAID-Platten von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1178
msgid "Cannot retrieve UUID, because it's an unnamed MD device object."
msgstr "Konnte die UUID nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:1184
#, python-format
msgid "Cannot retrieve UUID of %r, because the MD device doesn't exists."
msgstr "Konnte die UUID von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:1192
#, python-format
msgid "Getting the MD UUID from %r ..."
msgstr "Ermittle die MD UUID von %r ..."

#: pb_blockdev/md/device.py:1197
#, python-format
msgid "Cannot retrieve UUID of %(bd)r, because file %(file)r has no content."
msgstr "Konnte die UUID von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1205
msgid "Getting the MD UUID by 'mdadm --detail' ..."
msgstr "Ermittle die MD UUID durch 'mdadm --detail' ..."

#: pb_blockdev/md/device.py:1216
#, python-format
msgid "Could not interprete %(u)r as an UUID: %(m)s"
msgstr "Konnte %(u)r nicht als UUID interpretieren: %(m)s"

#: pb_blockdev/md/device.py:1241
#, python-format
msgid "Get details of %r ..."
msgstr "Ermittle Details von %r ..."

#: pb_blockdev/md/device.py:1258
msgid "Cannot retrieve sync states, because it's an unnamed MD device object."
msgstr "Konnte den Synchronisierungsstatus nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:1264
#, python-format
msgid "Cannot retrieve sync states of %r, because the MD device doesn't exists."
msgstr "Konnte den Synchronisierungsstatus von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:1275
#, python-format
msgid "Cannot retrieve sync state of %(bd)r, because file %(file)r has no content."
msgstr "Konnte den Synchronisierungsstatus von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1295
#, python-format
msgid "Cannot retrieve sync completion of %(bd)r, because file %(file)r has no content."
msgstr "Konnte Synchrinisierungskomplettierung von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1310
#, python-format
msgid "Could not detect sync speed: %r"
msgstr "Konnte Synchronisierungsgeschwindigkeit nicht ermitteln: %r"

#: pb_blockdev/md/device.py:1313
#, python-format
msgid "Cannot retrieve sync speed of %(bd)r, because file %(file)r has no content."
msgstr "Konnte Synchronisierungsgeschwindigkeit von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/md/device.py:1329
msgid "Cannot retrieve sub devices, because it's an unnamed MD device object."
msgstr "Konnte Sub-Geräte nicht ermitteln, da das MD Gerät keinen Namen hat."

#: pb_blockdev/md/device.py:1335
#, python-format
msgid "Cannot retrieve sub devices of %r, because the MD device doesn't exists."
msgstr "Konnte Sub-Geräte von %r nicht ermitteln, da das MD Gerät nicht existiert."

#: pb_blockdev/md/device.py:1343
#, python-format
msgid "Examining sub device dir %r ..."
msgstr "Untersuche Sub-Geräte von %r ..."

#: pb_blockdev/md/device.py:1373
#, python-format
msgid "Trying to stop the non-existing MD device %r."
msgstr "Habe versucht, das nicht existierende MD Gerät %r anzuhalten."

#: pb_blockdev/md/device.py:1380
#, python-format
msgid "Stopping MD device %r ..."
msgstr "Halte MD Gerät %r an ..."

#: pb_blockdev/md/device.py:1387
#, python-format
msgid "Could not stop MD raid %(m)r, got a return value of %(r)d."
msgstr "Konnte MD Gerät %(m)r nicht anhalten, da ich einen Rückgabewert von %(r)d erhalten habe."

#: pb_blockdev/md/device.py:1393
#, python-format
msgid "Checking, whether the device %r is really stopped ..."
msgstr "Schaue nach, ob das Gerät %r wirklich angehalten wurde ..."

#: pb_blockdev/md/device.py:1402
msgid "Stopped MD device %(m)r still exists after %0.2(s)f seconds."
msgstr "Das angehaltene Gerät %(m)r existiert noch nach %0.2(s)f Sekunden."

#: pb_blockdev/md/device.py:1407
#, python-format
msgid "Checking device %r for stopping again ..."
msgstr "Schaue nochmals nach, ob das Gerät %r angehalten wurde ..."

#: pb_blockdev/md/device.py:1413
msgid "Device %(m)r is really stopped after %0.2(s)f seconds."
msgstr "Das Gerät %(m)r wurde nach %0.2(s)f Sekunden tatsächlich angehalten."

#: pb_blockdev/md/device.py:1416
#, python-format
msgid "Device %r is really stopped."
msgstr "Das Gerät %r wurde tatsächlich angehalten."

#: pb_blockdev/md/device.py:1434
#, python-format
msgid "Trying to delete the non-existing MD device %r."
msgstr "Habe versucht, das nicht existierende MD Gerät %r zu löschen."

#: pb_blockdev/megaraid/enc.py:183 pb_blockdev/megaraid/enc.py:333
#: pb_blockdev/megaraid/enc.py:482 pb_blockdev/megaraid/enc.py:765
#, python-format
msgid "Comparision partner %(p)r is not a %(o)s object."
msgstr "Der Vergleichspartner %(p)r ist kein %(o)s Objekt."

#: pb_blockdev/megaraid/enc.py:604
msgid "The enclosure Id must be a positive integer value."
msgstr "Die Gehäuse Id muss eine positive Ganzzahl sein."

#: pb_blockdev/megaraid/enc.py:942
msgid "Analyzing lines:"
msgstr "Analysiere Zeilen:"

#: pb_blockdev/megaraid/enc.py:1022
#, python-format
msgid "Id of enclosure No %(enc)d: %(id)d."
msgstr "Id von Gehäuse Nummer %(enc)d: %(id)d."

#: pb_blockdev/megaraid/enc.py:1124
#, python-format
msgid "Found voltage sensor %d."
msgstr "Spannungssensor %d gefunden."

#: pb_blockdev/megaraid/enc.py:1138
#, python-format
msgid "Found voltage sensor status %r."
msgstr "Spannungssensorstatus %r gefunden."

#: pb_blockdev/megaraid/enc.py:1150
#, python-format
msgid "Found voltage sensor value %f."
msgstr "Spannungssensorwert %f gefunden."

#: pb_blockdev/megaraid/enc.py:1162
#, python-format
msgid "Found Fan %d."
msgstr "Lüfter %d gefunden."

#: pb_blockdev/megaraid/enc.py:1178
#, python-format
msgid "Found fan status %r."
msgstr "Lüfterstatus %r gefunden."

#: pb_blockdev/megaraid/enc.py:1188
#, python-format
msgid "Found fan speed %r."
msgstr "Lüftergeschwindigkeit %r gefunden."

#: pb_blockdev/megaraid/enc.py:1200
#, python-format
msgid "Found temperature sensor %d."
msgstr "Temperatursensor %d gefunden."

#: pb_blockdev/megaraid/enc.py:1214
#, python-format
msgid "Found temperature sensor status %r."
msgstr "Temperatursensor status %r gefunden."

#: pb_blockdev/megaraid/enc.py:1224
#, python-format
msgid "Found temperature value %d."
msgstr "Temperatur %d gefunden."

#: pb_blockdev/megaraid/handler.py:169
msgid "Searching for the MegaCLI command ..."
msgstr "Suche nach dem MegaCLI-Kommando ..."

#: pb_blockdev/megaraid/handler.py:182
msgid "Searching command in paths:"
msgstr "Suche Kommando in den Pfaden:"

#: pb_blockdev/megaraid/handler.py:189
#, python-format
msgid "Searching command %(cmd)r in %(dir)r ..."
msgstr "Suche Kommando %(cmd)r in %(dir)r ..."

#: pb_blockdev/megaraid/handler.py:194
#, python-format
msgid "Found %r ..."
msgstr "Fand %r ..."

#: pb_blockdev/megaraid/handler.py:199
#, python-format
msgid "File %r is not executable."
msgstr "Die Datei %r ist nicht ausführbar."

#: pb_blockdev/megaraid/handler.py:272
msgid "Retrieving number of MegaRaid controllers ..."
msgstr "Ermittle die Anzahl der MegaRaid-Controller ..."

#: pb_blockdev/megaraid/handler.py:284
#, python-format
msgid "Could not detect number of MegaRaid controllers in output of %r."
msgstr "Konnte die Anzahl der MegaRaid-Controller nicht in der Ausgabe %r ermitteln."

#: pb_blockdev/megaraid/handler.py:289
#, python-format
msgid "Found %d MegaRaid controller."
msgstr "%d MegaRaid-Controller gefunden."

#: pb_blockdev/megaraid/handler.py:323
#, python-format
msgid "Retrieving data of physical drive [%(pd)s] on MegaRaid controller %(a)d ..."
msgstr "Ermittle Daten von physikalischem Laufwerk [%(pd)s] an MegaRaid-Controller %(a)d ..."

#: pb_blockdev/megaraid/handler.py:333
#, python-format
msgid "PD [%(pd)s] (adapter %(a)d) doesn't exists."
msgstr "PD [%(pd)s] (Adapter %(a)d) existiert nicht."

#: pb_blockdev/megaraid/handler.py:373
#, python-format
msgid "Retrieving enclosures connected with MegaRaid controller %d ..."
msgstr "Ermittle Gehäuse, die mit dem MegaRaid-Controller %d verbunden sind ..."

#: pb_blockdev/megaraid/handler.py:384 pb_blockdev/megaraid/handler.py:465
#: pb_blockdev/megaraid/handler.py:574
msgid "Got:"
msgstr "Bekam:"

#: pb_blockdev/megaraid/handler.py:402
#, python-format
msgid "Starting with new enclosure No %d."
msgstr "Beginne mit neuem Gehäuse Nummer %d."

#: pb_blockdev/megaraid/handler.py:452
#, python-format
msgid "Retrieving logical drives of MegaRaid controller %d ..."
msgstr "Ermittle logische Laufwerke von MegaRaid-Controller %d ..."

#: pb_blockdev/megaraid/handler.py:486
#, python-format
msgid "Starting with new LD %(ld)r (target Id %(tid)r)."
msgstr "Beginne mit neuem logischen Laufwerk %(ld)r (Target Id %(tid)r)."

#: pb_blockdev/megaraid/handler.py:546
#, python-format
msgid "Parameter %(lbl)r %(val)r is not a %(cls)s object."
msgstr "Der Parameter %(lbl)r %(val)r is kein %(cls)s Objekt."

#: pb_blockdev/megaraid/handler.py:564
#, python-format
msgid "Retrieving infos about logical drive %(ld)d of MegaRaid controller "
      "%(adp)d ..."
msgstr "Ermittle Informationen über logisches Laufwerk %(ld)d an MegaRaid-Controller %(adp)d ..."

#: pb_blockdev/megaraid/handler.py:592
#, python-format
msgid "%s object:"
msgstr "%s-Objekt:"

#: pb_blockdev/megaraid/ld.py:169
msgid "The SCSI target Id must be a positive integer value."
msgstr "Die SCSI Target Id muss eine positive Integer-Zahl sein."

#: pb_blockdev/megaraid/ld.py:334
#, python-format
msgid "Comparision partner %r is not a Megaraid LogicalDrive object."
msgstr "Der Vergleichspartner %r ist kein Megaraid-LogicalDrive-Objekt."

#: pb_blockdev/megaraid/ld.py:522
#, python-format
msgid "RAID level of LD No %(nr)d: %(l)s."
msgstr "RAID-Level von LD Nr. %(nr)d: %(l)s."

#: pb_blockdev/megaraid/ld.py:531
#, python-format
msgid "Got %(n)r as name of LD %(nr)d."
msgstr "Habe %(n)r als Name von LD %(nr)d erhalten."

#: pb_blockdev/megaraid/ld.py:540
#, python-format
msgid "Got %(s)r as size of LD %(n)d."
msgstr "Habe %(s)r als Größe von LD %(n)d erhalten."

#: pb_blockdev/megaraid/ld.py:549
#, python-format
msgid "Got %(s)r as state of LD %(n)d."
msgstr "Habe %(s)r als Status von LD %(n)d erhalten."

#: pb_blockdev/megaraid/ld.py:581
#, python-format
msgid "Init of PD %(pd_nr)d [%(enc)d:%(slot)d] of LD %(nr)d."
msgstr "Initialisierung von PD %(pd_nr)d [%(enc)d:%(slot)d] von LD %(nr)d."

#: pb_blockdev/megaraid/ld.py:594 pb_blockdev/megaraid/ld.py:632
msgid "Got PD:"
msgstr "Erhaltenes PD:"

#: pb_blockdev/megaraid/ld.py:619
#, python-format
msgid "Init of PD [%(enc)d:%(slot)d] of LD %(nr)d."
msgstr "Initialisierung von PD [%(enc)d:%(slot)d] von LD %(nr)d."

#: pb_blockdev/megaraid/lds_app.py:59
#, python-format
msgid "%(prog)s [General options]"
msgstr "%(prog)s [Allgemeine Optionen]"

#: pb_blockdev/megaraid/lds_app.py:64
msgid "List of all logical drives of all MegaRaid adapters"
msgstr "Liste aller logischen Laufwerke aller MegaRaid-Adapter."

#: pb_blockdev/megaraid/lds_app.py:113
msgid "Output of found logical disks in a parsable format (CSV), without headers and footers"
msgstr "Ausgabe aller gefundenen logischen Laufwerke in im parsfähigen Format (CSV), "
"ohne Kopf- und Fußzeilen"

#: pb_blockdev/megaraid/lds_app.py:121
msgid "Retrieve the assigned hotspares and display them."
msgstr "Ermitteln der zugewiesenen Hotspare-Platten und ihre Darstellung."

#: pb_blockdev/megaraid/lds_app.py:141
msgid "No MegaRaid controllers found."
msgstr "Kein MegaRaid-Aadapter gefunden."

#: pb_blockdev/megaraid/lds_app.py:172
msgid "Got logical drives:"
msgstr "Gefundene logische Laufwerke:"

#: pb_blockdev/megaraid/lds_app.py:216
msgid "Total:"
msgstr "Insgesamt:"

#: pb_blockdev/multipath/__init__.py:71
#, python-format
msgid "Could not execute %r, because multipathd is not running as daemon."
msgstr "Konnte %r nicht ausführen, da kein multipathd-Daemon läuft."

#: pb_blockdev/multipath/device.py:247
#, python-format
msgid "Discovering multipath map %r ..."
msgstr "Erforsche Multipath-Gerät %r ..."

#: pb_blockdev/multipath/device.py:338
#, python-format
msgid "%(c)s on deleting multipath path %(p)r:"
msgstr "%(c)s beim Löschen des Multipath-Pfades %(p)r:"

#: pb_blockdev/multipath/device.py:343
#, python-format
msgid "Simulated removing of map %(m)r (%(n)s)."
msgstr "Simuliere Löschen von Multipath-Gerät %(m)r (%(n)s)."

#: pb_blockdev/multipath/device.py:351
#, python-format
msgid "Cannot delete map %(m)r (%(n)s), device %(d)r is still existing."
msgstr "Kann Multipath-Gerät %(m)r (%(n)s) nicht löschen, das Gerät %(d)r existiert immer noch."

#: pb_blockdev/multipath/path.py:154 pb_blockdev/multipath/path.py:262
#, python-format
msgid "The maximum wait time %r must be greater than zero."
msgstr "Die maximale Wartezeit %r muss größer als Null sein."

#: pb_blockdev/multipath/path.py:316 pb_blockdev/multipath/system.py:222
msgid "Using regex for multipathd paths:"
msgstr "Verwendete Regex für Multipath-Pfade:"

#: pb_blockdev/multipath/path.py:327 pb_blockdev/multipath/system.py:238
#, python-format
msgid "Checking line %r ..."
msgstr "Überprüfe Zeile %r ..."

#: pb_blockdev/multipath/path.py:358
#, python-format
msgid "Path %r is an already existing multipath path."
msgstr "Der Pfad %r ist bereits ein existierender Multipath-Pfad."

#: pb_blockdev/multipath/path.py:364
#, python-format
msgid "Device %r to add as multipath path does not exists."
msgstr "Das zum Hinzufügen als Multipath-Pfad vorgesehene Gerät %r existiert nicht."

#: pb_blockdev/multipath/path.py:374
#, python-format
msgid "Adding %r as multipath path ..."
msgstr "Füge %r als Multipath-Pfad hinzu ..."

#: pb_blockdev/multipath/path.py:382
#, python-format
msgid "Try no. %(try)d adding %(bd)r ..."
msgstr "Versuch Nummer %(try)d beim Hinzufügen von %(bd)r ..."

#: pb_blockdev/multipath/path.py:392
#, python-format
msgid "Simulated adding of %r."
msgstr "Simuliertes Hinzufügen von %r."

#: pb_blockdev/multipath/path.py:399 pb_blockdev/multipath/path.py:472
#: pb_blockdev/scsi.py:976
#, python-format
msgid "Looking for existence of %r ..."
msgstr "Schaue nach Existenz von %r ..."

#: pb_blockdev/multipath/path.py:402
#, python-format
msgid "Path %r seems to be added."
msgstr "Der Pfad %r scheint hinzugefügt worden zu sein."

#: pb_blockdev/multipath/path.py:406
#, python-format
msgid "Path %r is still not existing, next loop."
msgstr "Der Pfad %r existiert noch nicht, nächste Runde."

#: pb_blockdev/multipath/path.py:412
msgid "Path %(bd)r still not present after %0.2(time)f seconds."
msgstr "Der Pfad %(bd)r existiert nach %0.2(time)f Sekunden immer noch nicht."

#: pb_blockdev/multipath/path.py:439
#, python-format
msgid "Cannot remove path %r from multipath, because it isn't there."
msgstr "Konnte Pfad %r nicht löschen, da es bereits schon nicht mehr existiert."

#: pb_blockdev/multipath/path.py:444
#, python-format
msgid "Removing path %r from multipath ..."
msgstr "Entferne Pfad %r von Multipath ..."

#: pb_blockdev/multipath/path.py:455 pb_blockdev/scsi.py:964
#, python-format
msgid "Try no. %(try)d deleting %(bd)r ..."
msgstr "Versuch Nr. %(try)d des Löschens von %(bd)r ..."

#: pb_blockdev/multipath/path.py:465 pb_blockdev/scsi.py:972
#, python-format
msgid "Simulated removing of %r."
msgstr "Simuliertes Löschen von %r."

#: pb_blockdev/multipath/path.py:475
#, python-format
msgid "Path %r seems to be removed."
msgstr "Der Pfad %r scheint gelöscht worden zu sein."

#: pb_blockdev/multipath/path.py:479
#, python-format
msgid "Path %r is still existing, next loop."
msgstr "Der Pfad %r existiert immer noch, nächste Runde."

#: pb_blockdev/multipath/path.py:485
msgid "Path %(bd)r still present after %0.2(time)f seconds."
msgstr "Der Pfas %(bd)r existiert immer noch nach %0.2(time)f Sekunden."

#: pb_blockdev/multipath/system.py:130
msgid "Collecting from multipathd all known maps ..."
msgstr "Ermittle von multipathd alle bekannten Multipath-Geräte ..."

#: pb_blockdev/multipath/system.py:154 pb_blockdev/multipath/system.py:244
msgid "Match found."
msgstr "Übereinstimmung gefunden."

#: pb_blockdev/multipath/system.py:210
msgid "Collecting from multipathd all known paths ..."
msgstr "Ermittle von multipathd alle bekannten Pfade ..."

#: pb_blockdev/scsi.py:155 pb_blockdev/scsi.py:177
#, python-format
msgid "The maximum wait time for deleting %r must be greater than zero."
msgstr "Die maximale Wartezeit zum Löschen %r muss größer als Null sein."

#: pb_blockdev/scsi.py:282
#, python-format
msgid ""
"Cannot retrieve the blocking state of %(bd)r, because the file %(file)r "
"doesn't exists."
msgstr "Kann Blockstatus von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:287
#, python-format
msgid ""
"Cannot retrieve blocking state of %(bd)r, because no read access to %(file)r."
msgstr "Kann Blockstatus von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:292
#, python-format
msgid "Trying to retrieve the blocking state of %(bd)r from %(file)r."
msgstr "Versuche den Blockstatus von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:296
#, python-format
msgid ""
"Cannot retrieve blocking state of %(bd)r, because file %(file)r has no "
"content."
msgstr "Kann Blockstatus von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/scsi.py:423 pb_blockdev/scsi.py:517
msgid "unknown"
msgstr "unbekannt"

#: pb_blockdev/scsi.py:435
#, python-format
msgid ""
"Cannot retrieve the state of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann den Status von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:445
#, python-format
msgid "Trying to retrieve the state of %(bd)r from %(file)r."
msgstr "Versuche den Status von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:594
#, python-format
msgid "Directory %s not found."
msgstr "Verzeichnis %s nicht gefunden."

#: pb_blockdev/scsi.py:604
#, python-format
msgid "Search pattern: %r"
msgstr "Suchmuster: %r"

#: pb_blockdev/scsi.py:607
#, python-format
msgid ""
"Try %(no)d to retrieve the H:B:T:L numbers of the current SCSI device "
"%(dev)s ..."
msgstr "Versuch Nummer %(no)d, die H:B:T:L-Nummern des aktuellen SCSI-Gertätes %(dev)s zu ermitteln ..."

#: pb_blockdev/scsi.py:612
#, python-format
msgid "Found H:B:T:L numbers %r."
msgstr "Fand H:B:T:L-Nummern %r."

#: pb_blockdev/scsi.py:622
#, python-format
msgid "Could not retrieve H:B:T:L numbers of the current SCSI device %s."
msgstr "Kann H:B:T:L-Nummern des aktuellen SCSI-Gertätes %s nicht ermitteln."

#: pb_blockdev/scsi.py:638
#, python-format
msgid ""
"Cannot retrieve SCSI type id of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann SCSI-Typ von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:643
#, python-format
msgid ""
"Cannot retrieve SCSI type id of %(bd)r, because no read access to %(file)r."
msgstr "Kann SCSI-Typ von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:648
#, python-format
msgid "Trying to retrieve the numeric SCSI id of %(bd)r from %(file)r."
msgstr "Versuche die numerische SCSI-Id von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:652
#, python-format
msgid ""
"Cannot retrieve SCSI type id of %(bd)r, because file %(file)r has no content."
msgstr "Kann SCSI-Typ von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/scsi.py:669
#, python-format
msgid ""
"Cannot retrieve the vendor of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann Vendor von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:674
#, python-format
msgid "Cannot retrieve vendor of %(bd)r, because no read access to %(file)r."
msgstr "Kann Vendor von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:679
#, python-format
msgid "Trying to retrieve the vendor of %(bd)r from %(file)r."
msgstr "Versuche Vendor von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:683
#, python-format
msgid "Cannot retrieve vendor of %(bd)r, because file %(file)r has no content."
msgstr "Kann Vendor von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/scsi.py:700
#, python-format
msgid ""
"Cannot retrieve the model of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann Modell von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:705
#, python-format
msgid "Cannot retrieve model of %(bd)r, because no read access to %(file)r."
msgstr "Kann Modell von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:710
#, python-format
msgid "Trying to retrieve the model of %(bd)r from %(file)r."
msgstr "Versuche Modell von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:714
#, python-format
msgid "Cannot retrieve model of %(bd)r, because file %(file)r has no content."
msgstr "Kann Modell von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/scsi.py:731
#, python-format
msgid ""
"Cannot retrieve the revision of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann Revisionsnummer von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:736
#, python-format
msgid "Cannot retrieve revision of %(bd)r, because no read access to %(file)r."
msgstr "Kann Revisionsnummer von %(bd)r nicht ermitteln, da kein Lesezugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:741
#, python-format
msgid "Trying to retrieve the revision of %(bd)r from %(file)r."
msgstr "Versuche Revisionsnummer von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:757
#, python-format
msgid ""
"Cannot retrieve the SCSI level of %(bd)r, because the file %(file)r doesn't "
"exists."
msgstr "Kann Revisionsnummer von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/scsi.py:762
#, python-format
msgid ""
"Cannot retrieve SCSI level of %(bd)r, because no read access to %(file)r."
msgstr "Kann SCSI-Level von %(bd)r nicht ermitteln, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:767
#, python-format
msgid "Trying to retrieve the SCSI level of %(bd)r from %(file)r."
msgstr "Versuche SCSI-Level von %(bd)r aus %(file)r zu ermitteln."

#: pb_blockdev/scsi.py:771
#, python-format
msgid ""
"Cannot retrieve SCSI level of %(bd)r, because file %(file)r has no content."
msgstr "Kann SCSI-Level von %(bd)r nicht ermitteln, da die Datei %(file)r keinen Inhalt hat."

#: pb_blockdev/scsi.py:789
#, python-format
msgid "Cannot rescan %(bd)r, because the file %(file)r doesn't exists."
msgstr "Kann %(bd)r nicht neu scannen, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:794
#, python-format
msgid "Cannot rescan %(bd)r, because no write access to %(file)r."
msgstr "Kann %(bd)r nicht neu scannen, da kein Schreibzugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:798
#, python-format
msgid "Rescanning device '%s' ..."
msgstr "Scanne Gerät '%s' neu ..."

#: pb_blockdev/scsi.py:820
#, python-format
msgid "Cannot set %(bd)r online, because the file %(file)r doesn't exists."
msgstr "Kann %(bd)r nicht online setzen, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:825
#, python-format
msgid "Cannot set %(bd)r online, because no write access to %(file)r."
msgstr "Kann %(bd)r nicht online setzen, da kein Schreibzugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:829
#, python-format
msgid "Setting device '%s' online ..."
msgstr "Setze Gerät '%s' online ..."

#: pb_blockdev/scsi.py:852
#, python-format
msgid "Cannot set %(bd)r offline, because the file %(file)r doesn't exists."
msgstr "Kann %(bd)r nicht offline setzen, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:857
#, python-format
msgid "Cannot set %(bd)r offline, because no write access to %(file)r."
msgstr "Kann %(bd)r nicht offline setzen, da kein Schreibzugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:861
#, python-format
msgid "Setting device '%s' offline ..."
msgstr "Setze Gerät '%s' offline ..."

#: pb_blockdev/scsi.py:887
#, python-format
msgid "Cannot delete %(bd)r, because the file %(file)r doesn't exists."
msgstr "Kann Gerät %(bd)r nicht löschen, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi.py:892
#, python-format
msgid "Cannot delete %(bd)r, because no write access to %(file)r."
msgstr "Kann Gerät %(bd)r nicht löschen, da kein Schreibzugriff auf %(file)r besteht."

#: pb_blockdev/scsi.py:956
#, python-format
msgid "%s does not support recursive deletion."
msgstr "%s unterstützt kein rekursives Löschen."

#: pb_blockdev/scsi.py:897
msgid "Sleeping a half second ..."
msgstr "Schlafe ein halbes Sekündchen ..."

#: pb_blockdev/scsi.py:900
#, python-format
msgid "Deleting device %r ..."
msgstr "Lösche gerät %r ..."

#: pb_blockdev/scsi.py:930
#, python-format
msgid "Device %r is still existing, next loop."
msgstr "Gerät %r existiert noch, nächste Runde."

#: pb_blockdev/scsi.py:937
msgid "Device %(bd)r still present after %0.2(time)f seconds."
msgstr "Gerät %(bd)r ist nach %0.2(time)f Sekunden immer noch präsent."

#: pb_blockdev/scsi_host.py:292
#, python-format
msgid "Comparision partner %r is not a ScsiHost object."
msgstr "Der Vergleichspartner %r ist kein ScsiHost-Objekt."

#: pb_blockdev/scsi_host.py:320 pb_blockdev/scsi_host.py:325
#: pb_blockdev/scsi_host.py:342 pb_blockdev/scsi_host.py:347
#: pb_blockdev/scsi_host.py:364 pb_blockdev/scsi_host.py:369
#, python-format
msgid "Cannot retrieve %(what)s of %(of)r, %(target)r doesn't exists."
msgstr "Konnte %(what)s von %(of)r nicht ermitteln, da %(target)r nicht exitiert."

#: pb_blockdev/scsi_host.py:330 pb_blockdev/scsi_host.py:352
#: pb_blockdev/scsi_host.py:374
#, python-format
msgid "Cannot retrieve %(what)s of %(of)r, %(target)r is not readable."
msgstr "Konnte %(what)s von %(of)r nicht ermitteln, da %(target)r nicht lesbar ist."

#: pb_blockdev/scsi_host.py:365 pb_blockdev/scsi_host.py:370
#: pb_blockdev/scsi_host.py:375
msgid "state"
msgstr "Status"

#: pb_blockdev/scsi_host.py:398
#, python-format
msgid "Search pattern for LUNs: %r ..."
msgstr "Suchmuster für LUN: %r ..."

#: pb_blockdev/scsi_host.py:404
#, python-format
msgid "Checking LUN directory %r ..."
msgstr "Überprüfe LUN-Verzeichnis %r ..."

#: pb_blockdev/scsi_host.py:410
#, python-format
msgid "%r is not a valid HBTL address:"
msgstr "%r ist keine gültige HBTL-Adresse:"

#: pb_blockdev/scsi_host.py:463
#, python-format
msgid "Found blockdevice dirs: %s"
msgstr "Fand Verzeichnis für Blockgeräte: %s"

#: pb_blockdev/scsi_host.py:470
#, python-format
msgid "Found blockdevice %(bd)r for '%(h)d:%(b)d:%(t)d:%(l)d'."
msgstr "Fand Blockgerät %(bd)r für '%(h)d:%(b)d:%(t)d:%(l)d'."

#: pb_blockdev/scsi_host.py:543
#, python-format
msgid "HBTL host Id %(hh)d does not match current host Id %(hc)d."
msgstr "Die HBTL Host-Id %(hh)d stimmt nicht mit der aktuellen SCSI host Id %(hc)d überein."

#: pb_blockdev/scsi_host.py:583
#, python-format
msgid "Scanning SCSI host %(hn)r with %(ss)r ..."
msgstr "Scanne den SCSI-Host %(hn)r mit %(ss)r ..."

#: pb_blockdev/scsi_host.py:588
#, python-format
msgid "Cannot scan SCSI host %(hn)r, because the file %(file)r doesn't exists."
msgstr "Kann SCSI-Host %(hn)r nicht scannen, da die Datei %(file)r nicht existiert."

#: pb_blockdev/scsi_host.py:594
#, python-format
msgid "Cannot scan SCSI host %(hn)r, because no write access to %(file)r."
msgstr "Kann SCSI-Host %(hn)r nicht scannen, da kein Schreibzugriff auf %(file)r zugelassen ist."

#: pb_blockdev/scsi_host.py:620
#, python-format
msgid "Object %r is not a HBTL object."
msgstr "Das Objekt %r ist kein HBTL-Objekt."

#: pb_blockdev/scsi_host.py:626
#, python-format
msgid "Device %(d)r for HBTL %(h)r already exists."
msgstr "Das Gerät %(d)r für die HBTL-Adresse %(h)r existiert bereits."

#: pb_blockdev/scsi_host.py:644
#, python-format
msgid "Try number %(t)d for detecting SCSI device with HBTL %(h)r ..."
msgstr "Versuche Nummer %(t)d für die Ermittlung des SCSI-Gerätes mit der HBTL-Adresse %(h)r ..."

#: pb_blockdev/scsi_host.py:649
#, python-format
msgid "Found device %(d)s for HBTL %(h)r after %(t)d tries."
msgstr "Gerät %(d)s für die HBTL-Adresse %(h)r nach %(t)d Versuchen gefunden."

#: pb_blockdev/scsi_host.py:657
#, python-format
msgid "No device appeared for HBTL %(h)r after %(t)d tries in %(s)0.2f seconds."
msgstr "Kein Gerät für die HBTL-Adresse %(h)r nach %(t)d Versuchen in %(s)0.2f Sekunden aufgetaucht."

#: pb_blockdev/scsi_host.py:494
#, python-format
msgid "Searching for SCSI hosts with pattern %r ..."
msgstr "Suche nach SCSI-Hosts mit Suchmuster %r ..."

#: pb_blockdev/scsi_host.py:502
#, python-format
msgid "Invalid scsi_host directory %r found."
msgstr "Ungültiges Verzeichnis %r für SCSI-Host gefunden."

#: pb_blockdev/translate.py:40
#, python-format
msgid "Basedir: %r"
msgstr "Basisverzeichnis: %r"

#: pb_blockdev/translate.py:41
#, python-format
msgid "Found .mo-file: %r"
msgstr "Gefundene .mo-Datei: %r"
